Tweak sleep behavior to avoid oversleep
FNA-XNA/FNA pull request #357
Opened 2021-07-18 08:24 UTC by thatcosmonaut

We had a complaint about input latency on the FNA version of Celeste compared to the XNA version. I investigated using the Vulkan renderer and ruled out rendering and presentation. When I removed the sleep from Tick(), the reported input latency vanished. Schedulers have a tendency to wake up the thread early, so it is likely that by sleeping until we reach the full timestep amount we are oversleeping by the sleep resolution amount of the operating system. However, busywaiting is not exactly ideal, so I propose a compromise.

This patch makes it so that we attempt to sleep for the full fixed timestep amount remaining. Because schedulers usually wake us up early, and sleep resolution is finite, we have a "no sleep threshold" value. If we still have time to wait, but that time is shorter than the "no sleep threshold", then we do not sleep, but we do not perform Update() either. This allows the next fixed timestep to happen accurately without wasting too many CPU cycles.

This changed behavior causes Draw() to run every loop until the next Update() is performed, which is pointless and wastes GPU resources, so Draw() is now only called from Tick() if an updated has actually been performed.

2021-07-18 14:00 UTC, flibitijibibo requested changes
Trying to adjust for the timer resolution makes sense, but it's going to take a lot of work to figure this value out.

2021-07-18 14:00 UTC, flibitijibibo commented on src/Game.cs
> +			TimeSpan noSleepThreshold = TimeSpan.FromMilliseconds(4);
We should look into this and see if we can find a definitive value instead - this could make systems with even lower resolutions unplayable.

2021-07-18 16:21 UTC, thatcosmonaut commented on src/Game.cs
> +			if (!updated || suppressDraw)
See my original explanation - if we don't do this, then imagine the game wakes us up from sleep early and we are too close to sleep again. The game will then render like 100 times or whatever while we wait for the next timestep to kick in even though the game hasn't updated, which doesn't really make sense.

2021-07-18 19:52 UTC, flibitijibibo commented
Marking as a draft until we have the timer resolution function. The draw thing can go in a separate patch if needed.

2021-07-18 23:15 UTC, thatcosmonaut commented
PR has been submitted to SDL: https://github.com/libsdl-org/SDL/pull/4511

2021-07-20 02:14 UTC, thatcosmonaut commented
New strategy:

- While we are less than the elapsed time + estimated sleep precision, request 1ms sleeps
- Check how long we actually slept after requesting 1ms to update our estimated sleep precision
- When we are close enough to sleep precision, spinwait until we hit elapsed time

2021-07-20 02:23 UTC, thatcosmonaut commented
We probably need an undersleep threshold so we bail out of spinwait earlier rather than later. Will propose an undersleep value after some testing.

2021-07-20 04:53 UTC, thatcosmonaut commented
Superseded by https://github.com/FNA-XNA/FNA/pull/358

2021-07-20 04:53 UTC, closed without merging