Add Srgb render target support
FNA-XNA/FNA pull request #362
Opened 2021-09-11 19:43 UTC by bartwe

2021-09-11 20:00 UTC, flibitijibibo requested changes
Need to undo the submodule update and fix tabbing, otherwise fine

2021-09-12 14:59 UTC, bartwe commented
How do you mean 'undo the submodule?' it contains required changes

2021-09-12 18:16 UTC, flibitijibibo commented
We have to use the revision that gets merges into the master branch first - I'll merge that first, then we can use that revision for this patch.

2021-09-12 19:30 UTC, flibitijibibo requested changes
Couple minor things...

2021-09-12 19:30 UTC, flibitijibibo commented on src/Graphics/SurfaceFormat.cs
> +    }
```suggestion
	}
```

2021-09-12 19:30 UTC, flibitijibibo commented on src/Graphics/GraphicsAdapter.cs
> +				format != SurfaceFormat.ColorSrgbEXT &&
Should be at the bottom of the list

2021-12-27 19:20 UTC, flibitijibibo commented
Wrote in the bare minimum since this took too long... should be enough unless someone's hacking into ProfileCapabilities:

https://github.com/FNA-XNA/FNA/commit/7fb834b7ad59d81d2b3eb783f7673fb1d0c6e3e5

2021-12-27 19:20 UTC, closed without merging